# Generated by Django 4.2.9 on 2024-02-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_lessonslot_is_available_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
