# Generated by Django 4.2.10 on 2024-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='files/assignment_files/')),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to='images/assignment_images/')),
                ('checked', models.BooleanField(default=False)),
                ('handed', models.BooleanField(default=False)),
                ('response_content', models.CharField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='files/response_files/')),
            ],
        ),
    ]
