# Generated by Django 4.2.10 on 2024-04-10 22:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField()),
                ('attached_files', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='files/assignment_files/'), blank=True, null=True, size=None)),
                ('attached_images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/assignment_images/'), blank=True, null=True, size=None)),
                ('checked', models.BooleanField(default=False)),
                ('handed', models.BooleanField(default=False)),
            ],
        ),
    ]
