# Generated by Django 4.2.10 on 2024-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attached_files',
            field=models.FileField(blank=True, null=True, upload_to='files/assignment_files/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attached_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/assignment_images/'),
        ),
    ]
