# Generated by Django 4.2.10 on 2024-04-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0004_alter_assignment_attached_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='attached_files',
            new_name='attached_file',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='attached_images',
            new_name='attached_image',
        ),
    ]
