# Generated by Django 4.2.10 on 2024-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0005_rename_attached_files_assignment_attached_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='response_content',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='files/response_files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='response_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/response_images/'),
        ),
    ]
