# Generated by Django 4.2.10 on 2024-04-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0006_assignment_response_content_assignment_response_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='response_image',
        ),
    ]
