# Generated by Django 4.2.10 on 2024-04-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0007_remove_assignment_response_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='response_content',
            field=models.CharField(blank=True, null=True),
        ),
    ]
